#%RAML 0.8
title: twilio
version: 1.0
/sendText:
  displayName: resourceName
  get:
    queryParameters:
      phoneNumber:
        description: This phone number MUST be authorized on the twilio site.  You can't just enter any number!
        type: string
        example: 212-111-2345
      textMessage:
        description: The message can be anything you want.
        type: string
        example: Hello World
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message":"text sent"
              }
