#%RAML 0.8
title: Employee API
version: 1.0
#baseUri: http://localhost:8082/api/{version}
baseUri: http://mocksvc.mulesoft.com/mocks/61092c53-feac-4945-baa5-ed0ecc816348/api/{version}
documentation: 
  - title: Employee API
    content: Employee Information Creation, Retrieval, Update and Deletion Services
/employees:
  displayName: Employees
  put:
    description: Update employee 
    body:
      application/json:
        schema: !include employee_schema.json
        example: !include employee.json      
    responses:
      201: !!null    
